### PR TITLE
Fix changes from code review

### PR DESCRIPTION
**Pull request by MephistoDevelop**
Features Fixed:
-Fix misspell errors
-Change branch name

### CODE REVIEW

**Comment by shshamim63** [comment]
## Status :spades: Required Changes :spades: 
___
Hi @MephistoDevelop and @thcdevcl :wave: ,
Awesome job :clap: . Readme contains how to start with the game, setup the game, prerequisites. But need to modify the readme a little bit more. So follow the instructions below to complete this project.
___
### Mandatory Changes
___
1. Neither I can see Javascript or neither I can see webpack configuration, so why it is mentioned in here
image
2. I am not that much expert in grammar, but this sentence seems imbalanced to me. 
image

You can say something like- To start using this project ..... on the prerequisites section. 
3. You have added a invalid screenshot. Either fix that, or you can remove it.
4. The live demo link is not functional. Same either fix that, or you can remove it.
___
#### Do not merge this pull request. For each milestone you have to maintain a PR. So please fix the above mentioned issue and send another review request. 
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

**Comment by MephistoDevelop** [comment]
By error  i merged the branch but  already did the changes that you suggest me before.

**Review by stratospherique — COMMENTED** [review]
### Great work @team :clap: However, the changes need to be made on the Readme file in order to get approval for the project. Check :arrow_down: 

* [x] The screenshot is not showing. :pray: fix it
- **[REQUIRED]** Since you mistakenly have merged this pull request. I suggest doing the following:
  - Create a new Branch (readme branch) starting from `development` branch.
  - Make the suggested changes
  - Open a new pull request
  - Submit a code review form

Happy coding :v: 
**Ahmed Mahfoudh**

**Comment by MephistoDevelop** [comment]
Sure , but by error y paste the wrong direction from new code review it was the new link:
https://github.com/MephistoDevelop/tictac/pull/23/

**Comment by stratospherique** [comment]
Hi @MephistoDevelop . If you have submitted a code review request with the new link then it's fine we will review it soon. If not please do.

**Comment by MephistoDevelop** [comment]
sure !, can you change the button to send new pull with the new link please ?

**Pull request merged**
